SELECT * FROM IPLPLAYERS;

# total spendings on players for each team
SELECT TEAM, SUM(PRICE_IN_CR) AS TOTAL_SPENDING FROM IPLPLAYERS 
GROUP BY TEAM
ORDER BY TOTAL_SPENDING DESC;

# top 3 highest paid 'all rounders' across all teams
SELECT TEAM, PLAYER, PRICE_IN_CR
FROM IPLPLAYERS
WHERE ROLE = 'ALL-ROUNDER'
ORDER BY PRICE_IN_CR DESC
LIMIT 3;

#highest priced player in each team
SELECT TEAM, PLAYER, 
PRICE_IN_CR 
FROM IPLPLAYERS P1
WHERE PRICE_IN_CR = (
	SELECT MAX(PRICE_IN_CR) 
    FROM IPLPLAYERS P2
    WHERE P1.TEAM = P2.TEAM)
ORDER BY TEAM DESC;

# rank the players by their price within each team and list top 2 for every team
SELECT * FROM ( SELECT TEAM, PLAYER, PRICE_IN_CR,
ROW_NUMBER() OVER (PARTITION BY TEAM ORDER BY PRICE_IN_CR DESC) AS RANK_WITHIN_TEAM 
FROM IPLPLAYERS) x
WHERE RANK_WITHIN_TEAM <= 2 ;

WITH RANKED_PLAYERS AS (SELECT TEAM, PLAYER, PRICE_IN_CR,
ROW_NUMBER() OVER (PARTITION BY TEAM ORDER BY PRICE_IN_CR DESC) AS RANK_WITHIN_TEAM 
FROM IPLPLAYERS)
SELECT TEAM, PLAYER, PRICE_IN_CR, RANK_WITHIN_TEAM
FROM RANKED_PLAYERS
WHERE RANK_WITHIN_TEAM <= 2
ORDER BY TEAM DESC;

#most expensive player in each team along with the second most expensive player's name and price
# second most expensive player in column
SELECT TEAM, PLAYER,PRICE_IN_CR FROM (
	SELECT TEAM, PLAYER, PRICE_IN_CR,
	ROW_NUMBER() OVER(PARTITION BY TEAM ORDER BY PRICE_IN_CR DESC) AS PRICE_RANK
    FROM IPLPLAYERS) x
WHERE PRICE_RANK <= 2;

# second most expensive player in row
WITH RANK_PLAYERS AS(
	SELECT PLAYER, TEAM, PRICE_IN_CR,
    ROW_NUMBER() OVER (PARTITION BY TEAM ORDER BY PRICE_IN_CR DESC) AS RANK_WITHIN_TEAM
    FROM IPLPLAYERS)
SELECT TEAM, 
		MAX(CASE WHEN RANK_WITHIN_TEAM = 1 THEN PLAYER END) AS MOST_EXPENSIVE_PLAYER,
        MAX(CASE WHEN RANK_WITHIN_TEAM = 1 THEN PRICE_IN_CR END) AS HIGHEST_PRICE,
        MAX(CASE WHEN RANK_WITHIN_TEAM = 2 THEN PLAYER END) AS SECOND_MOST_EXP_PLAYER,
        MAX(CASE WHEN RANK_WITHIN_TEAM = 2 THEN PRICE_IN_CR END) AS SECOND_HIGHEST_PRICE
FROM RANK_PLAYERS
GROUP BY TEAM;

# calculate the percentage contribution of each player's price to their team's total spending
SELECT PLAYER, TEAM, PRICE_IN_CR,
CAST((PRICE_IN_CR / SUM(PRICE_IN_CR) OVER (PARTITION BY TEAM)) * 100 AS DECIMAL(10,2) ) AS CONTRIBUTION_PERCENTAGE
FROM IPLPLAYERS
ORDER BY TEAM, CONTRIBUTION_PERCENTAGE DESC;

# classify players as 'high', 'medium' or 'low' based on the following rules
-- high : price >= 15C
-- medium: 5C<= price < 15C
-- low : price<5C
-- and find the number of players in each bracket

WITH PRICE_RANGE AS(
SELECT TEAM, PLAYER, PRICE_IN_CR,
CASE
WHEN PRICE_IN_CR >= 5 AND PRICE_IN_CR < 15 THEN 'MEDIUM'
WHEN PRICE_IN_CR >= 15 THEN 'HIGH'
ELSE 'LOW'
END AS PRICE_CATEGORY
FROM IPLPLAYERS)
SELECT TEAM, PRICE_CATEGORY, COUNT(PRICE_CATEGORY) AS NO_OF_PLAYERS
FROM PRICE_RANGE
GROUP BY TEAM, PRICE_CATEGORY;

# find the average price of indian players and compare it with overseas players using a subquery
SELECT * FROM IPLPLAYERS;

SELECT 
	'OVERSEAS' AS PLAYERTYPE, 
(SELECT AVG(PRICE_IN_CR) 
FROM IPLPLAYERS
WHERE TYPE LIKE 'OVERSEAS%') AS AVG_PRICE
UNION ALL
SELECT 
	'INDIAN' AS PLAYERTYPE,
(SELECT AVG(PRICE_IN_CR)
FROM IPLPLAYERS
WHERE TYPE LIKE 'INDIAN%') AS AVG_PRICE;
 
# identify players who earn more than the avg of their team
WITH TEAM_WISE_AVG AS (SELECT PLAYER, TEAM, PRICE_IN_CR,
AVG(PRICE_IN_CR) OVER (PARTITION BY TEAM) AS AVG_PRICE_OF_TEAM
FROM IPLPLAYERS)
SELECT PLAYER, TEAM, PRICE_IN_CR
FROM TEAM_WISE_AVG 
WHERE PRICE_IN_cR > AVG_PRICE_OF_TEAM;

# for each role, find the most expensive player and their price 
SELECT * FROM IPLPLAYERS;

SELECT ROLE FROM IPLPLAYERS GROUP BY ROLE;

SELECT ROLE, PLAYER, PRICE_IN_CR 
FROM IPLPLAYERS P1
WHERE PRICE_IN_CR = (
	SELECT MAX(PRICE_IN_CR)
    FROM IPLPLAYERS P2
    WHERE P2.ROLE = P1.ROLE)
ORDER BY ROLE;